name: think-link

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: sleep infinity
    secrets:
      - pg_password
    volumes:
      - .:/app
    env_file: .envs/api.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    env_file: .envs/postgres.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  pg_password:
    file: ./docker/secrets/postgres_password.txt

volumes:
  pg_data: {}
