name: tests

on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches: ["dev", "main"]

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.15"
          enable-cache: true

      - name: Install the project
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest

